# Generated by Django 4.2.1 on 2023-06-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='ordernumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
