# Generated by Django 4.2.1 on 2023-06-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_color_size_product_variant_alter_comment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='image',
        ),
        migrations.AddField(
            model_name='variants',
            name='image_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
